sudo: false

language: python

python:
    - "2.7"

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -y realpath

script: ./travis_build.sh
