sudo: false

language: python

addons:
    apt:
        packages:
            - realpath

python:
    - "2.7"

notifications:
  email:
    on_success: never
    on_failure: always

script: ./travis_build.sh
